spring.application.name=dt-finma
# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/spfm_db
spring.datasource.username=spfm_user
spring.datasource.password=spfm_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=aaaf672d2323ed6375b573fd0e81265ca513987e9d930497a2dc949e7709bf50
app.jwt.expiration-ms=86400000